name: medicines_value_monitor
version: "1.0.0"
profile: medicines_value_monitor

models:
  medicines_value_monitor:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

seeds:
  medicines_value_monitor:
    low_value_medicines:
      +column_types:
        category: varchar
        bnf_code_like: varchar
        is_exclusion: boolean
        note: varchar
    brand_exceptions:
      +column_types:
        bnf_code_like: varchar
        drug: varchar
        reason: varchar
